aloha-agilex:
  file_path: "/home/anker/robotwin/Pi0-RL-RoboTwin/assets/embodiments/aloha-agilex/"

piper:
  file_path: "/home/anker/robotwin/Pi0-RL-RoboTwin/assets/embodiments/piper"

franka-panda:
  file_path: "/home/anker/robotwin/Pi0-RL-RoboTwin/assets/embodiments/franka-panda/"

ARX-X5:
  file_path: "/home/anker/robotwin/Pi0-RL-RoboTwin/assets/embodiments/ARX-X5"

ur5-wsg:
  file_path: "/home/anker/robotwin/Pi0-RL-RoboTwin/assets/embodiments/ur5-wsg"
